### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jakee246/project4#1]
This unfortunately doesn't meet [the requirements of the project](http://codekwondo.herokuapp.com/showcases/321). All of your assets are 404ing, because they're not in a public folder, and there's only one column instead of 2. Frankly, this is very sloppy. You must read the project criteria fully and you must test your app before submitting. Please fix this.

If you're not sure how, it is your responsibility to ask questions in a timely manner to get projects done in time. I'd like this fixed before the end of the day tomorrow, or else this project will result in [a strike](https://github.com/chrisvfritz/tc359_syllabus#not-trying).

**Comment by jakee246** [comment]
https://tc359project4.herokuapp.com/

Corrected the coding and the HTML is validated.

Thank you.

**Comment by chrisvfritz** [comment]
:+1: Much better.

## Points of improvement for future projects

### Inconsistent indentation

I do notice some inconsistent indentation in some files, which I'd like you to try to clean up in future projects. Let me know if you're not sure what I mean or how you'd fix it.
